// <auto-generated />
namespace ProyectoIntegrador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class citas_medico_nulleable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(citas_medico_nulleable));
        
        string IMigrationMetadata.Id
        {
            get { return "202105090401193_citas_medico_nulleable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
