// <auto-generated />
namespace ProyectoIntegrador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tipo_citas_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipo_citas_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202105120034230_tipo_citas_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
