// <auto-generated />
namespace ProyectoIntegrador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajustedepmun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustedepmun));
        
        string IMigrationMetadata.Id
        {
            get { return "202104231325568_ajuste-dep-mun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
