// <auto-generated />
namespace ProyectoIntegrador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class partial_01_08_03_21_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partial_01_08_03_21_3));
        
        string IMigrationMetadata.Id
        {
            get { return "202103180123341_partial_01_08_03_21_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
