// <auto-generated />
namespace ProyectoIntegrador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajustetipousuariosafiliados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustetipousuariosafiliados));
        
        string IMigrationMetadata.Id
        {
            get { return "202105091802050_ajuste-tipo-usuarios-afiliados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
